version: '3.8'

services:

  web:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app:rw
    ports:
      - "8000:8000"

    restart: always
    networks:
      - main
  
  nginx:
    container_name: nginx_hci
    build:
      context: ./nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
    networks:
      - main
  
volumes:
networks:
  main: