version: '3.8'

services:

  web:
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app:rw
    ports:
      - "8000:8000"

    restart: always
    networks:
      - main
  
  quizapp:
    container_name: hci_normal
    build:
      context: ./quizapp/frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
    networks:
      - main

  quizapp-noAssistance:
    container_name: hci_noAssistance
    build:
      context: ./quizapp-noAssistance/frontend
    ports:
      - "3001:3001"
    depends_on:
      - web
    networks:
      - main

  quizapp-prompted:
    container_name: hci_prompted
    build:
      context: ./quizapp-prompted/frontend
    ports:
      - "3002:3002"
    depends_on:
      - web
    networks:
      - main

  nginx:
    container_name: nginx_hci
    build:
      context: ./nginx/
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
      - quizapp
      - quizapp-noAssistance
      - quizapp-prompted
    restart: always
    networks:
      - main
  
volumes:
networks:
  main: